### ISSUE TITLE
In PoseEstNet, how to change the test data set through settings during testing 

### ISSUE THREAD

**Issue by lhc11171552** [NVlabs/PAMTRI#2]

**Comment by zhengthomastang** [comment]
Hi @lhc11171552 . Thank you for your interests in our work. You can prepare the test data in the same format as given in our README file: https://github.com/NVlabs/PAMTRI/tree/master/PoseEstNet. And then follow the instructions of testing for your corresponding dataset.

**Comment by lhc11171552** [comment]
thank you very much

**Comment by lhc11171552** [comment]
Thank you very much. I tested the veri data set in your way, but the result of the test is only the marked part of the test data. If I want to test the veri data set or other data sets, such as the part of the data that is not marked, I want How to set in the yaml file (hope to use veri data as an example) thank you very much



发自我的iPhone


------------------ Original ------------------

**Comment by superWSL** [comment]
Hello, have you reproduced the code for post estimation? When I run test.py for testing, the following error is reported. What is the reason?
### ### ****
=> loading model from models/veri/pose_hrnet/w32_256x256_adam_lr1e-3/model_best.pth
=> load 1060 samples
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
Traceback (most recent call last):
  File "tools/test.py", line 148, in <module>
    main()
  File "tools/test.py", line 140, in main
    final_output_dir, tb_log_dir)
  File "/home/wangsiling/PAMTRI/PoseEstNet/tools/../lib/core/function.py", line 121, in validate
    for i, (input, target, target_weight, meta) in enumerate(val_loader):
  File "/home/wangsiling/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/wangsiling/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
    raise batch.exc_type(batch.exc_msg)
cv2.error: Traceback (most recent call last):
  File "/home/wangsiling/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangsiling/anaconda3/envs/HRNet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wangsiling/PAMTRI/PoseEstNet/tools/../lib/dataset/JointsDataset.py", line 86, in __getitem__
    data_numpy = cv2.cvtColor(data_numpy, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by zhengthomastang** [comment]
@superWSL The error indicates that your input color image, which should have 3 or 4 color channels (BGR format in this case), does not have the correct number of channels. Please print out the shape of `data_numpy` to check whether there is anything wrong with the image format.

**Comment by superWSL** [comment]
Thank you for your answer. When I output the image path parameter image_file of this line of `data_numpy = cv2.imread(
                image_file, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION
            )` ,the output result is as follows, it seems that there is an error in the read image part. 
The test data set of the veri data set has 13257 images, but there are only 1060 image annotations in the csv annotation file. I wonder if the images in the test set should be filtered out according to the image names in the annotation file?

### ### ### 
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0020_c017_00039045_0.jpg
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0010_c014_00034990_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0040_c014_00011910_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0050_c018_00071285_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0080_c019_00077460_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0190_c016_00051020_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0200_c004_00045140_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0220_c012_00015230_0.jpg
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0250_c012_00080255_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0210_c008_00072860_0.jpg
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0290_c003_00027780_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0330_c001_00045105_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0330_c014_00041965_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0350_c001_00014365_0.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0350_c019_00015575_0.jpg
/home/wangsiling/PAMTRI/PoseEstNet/data/veri/images/image_test/0350_c013_00059905_0.jpg

**Comment by zhengthomastang** [comment]
@superWSL Please also print out the shapes of the images besides the image names to root-cause the issue. For pose estimation, please only train and validate on the subset with labels.

**Comment by superWSL** [comment]
Hello, this error occurred because I used the pictures in the image_test folder of the veri data set for testing. When I changed to use the pictures in the image_train folder for testing, the error did not appear.
