### ISSUE TITLE
Thank you very much. I tested the veri data set in your way, but the result of the test is only the marked part of the test data. If I want to test the veri data set or other data sets, such as the part of the data that is not marked, I want How to set in the yaml file (hope to use veri data  as an example)

### ISSUE THREAD

**Issue by lhc11171552** [NVlabs/PAMTRI#3]

**Comment by zhengthomastang** [comment]
It seems you are using the code for inference only instead of evaluation. You may remove the argument `--evaluate` for your purpose and run on the VeRi test set. The argument `--outputPreds` enables the output of predicted pose (keypoints), heatmaps and segments, where the output directory is specified by `--outputDir output`. In the output CSV file of pose (keypoints), the format of each line is defined in the README file.

**Comment by lhc11171552** [comment]
Thank you very much. In fact, I mean During the PoseEstNet test，how to input the training data and test data of the veri dataset to get the key point heatmap of the veri training data and the test data . How should this be set in yaml, because in github Did not mention this



发自我的iPhone


------------------ Original ------------------

**Comment by zhengthomastang** [comment]
All you need is to change `DATASET: ROOT` and `DATASET: TEST_SET` to point to the corresponding directory of images that you want to inference.

**Comment by lhc11171552** [comment]
thank you very much，thanks



发自我的iPhone


------------------ Original ------------------

**Comment by lhc11171552** [comment]
If I use own dataset for testing, did i still need to mark the key points of my own dataset?



发自我的iPhone


------------------ Original ------------------

**Comment by zhengthomastang** [comment]
The labeling input is not necessary if you are using the model for inference only.

**Comment by lhc11171552** [comment]
Thank you so much for returning my message so late. But in PoseEstNet's yaml, once I modify the TEST_SET to another data set without annotations, the program will report an error saying that the read pictures are inconsistent. I am very troubled, why this error occurs. Can you tell me the correct yaml format (take the veri dataset as an example). I modified the yaml file in the way you told me above, but still reported an error



发自我的iPhone


------------------ Original ------------------

**Comment by zhengthomastang** [comment]
Can you share the command that you ran besides modifying the yaml file?

**Comment by lhc11171552** [comment]
The command I tested is python tools/test.py --outputPreds --outputDir output --cfg experiments/veri/hrnet/w32_256x256_adam_lr1e-3.yaml TEST.MODEL_FILE models/veri/pose_hrnet/w32_256x256_adam_lr1e-3/model_best.pth. But once I modify the test file in TEST_SET to the yaml file in veri, an error will be reported. The error is: FileNotFoundError: [Errno 2] No such file or directory:'data/veri/annot/label_yaml.csv'.

**Comment by lhc11171552** [comment]
Sorry, I typed the wrong English above, not yaml, but the query file in veri instead of the test file

**Comment by lhc11171552** [comment]
The error is: FileNotFoundError: [Errno 2] No such file or directory:'data/veri/annot/label_query.csv'

**Comment by lhc11171552** [comment]
The command I tested is python tools/test.py --outputPreds --outputDir output --cfg experiments/veri/hrnet/w32_256x256_adam_lr1e-3.yaml TEST.MODEL_FILE models/veri/pose_hrnet/w32_256x256_adam_lr1e-3/model_best.pth. But once I modify the test file in TEST_SET to the query file in veri, an error will be reported. The error is: FileNotFoundError: [Errno 2] No such file or directory:'data/veri/annot/label_query.csv

**Comment by zhengthomastang** [comment]
@lhc11171552 Sorry for the confusion. Please see the lines [here](https://github.com/NVlabs/PAMTRI/blob/master/PoseEstNet/lib/core/function.py#L288-L296). When enabling `--outputPreds`, the `label_XXX.csv` file is necessary as an input but only the first column is required (image names).

**Comment by lhc11171552** [comment]
Thank you very much. I did what you said, but I still got an error. The error is: => loading model from models/veri/pose_hrnet/w32_256x256_adam_lr1e-3/model_best.pth
Traceback (most recent call last):
   File "tools/test.py", line 149, in <module>
     main()
   File "tools/test.py", line 127, in main
     normalize,
   File "/home/w/lhc/PoseEstNet/tools/../lib/dataset/veri.py", line 40, in __init__
     self.db = self._get_db()
   File "/home/w/lhc/PoseEstNet/tools/../lib/dataset/veri.py", line 59, in _get_db
     joint = [int(row[j*3+3]), int(row[j*3+4]), int(row[j*3+5])]
IndexError: list index out of range

**Comment by zhengthomastang** [comment]
Thanks for letting us know. The datasets have to be loaded with all the required fields image names, width, height and joints (see [here](https://github.com/NVlabs/PAMTRI/blob/master/PoseEstNet/lib/dataset/veri.py#L50-L61)). But the joints will not be used for evaluation. You can put in dumb values as placeholders in the label CSV file.

**Comment by lhc11171552** [comment]
Will the width and height of the image be used for evaluation?

**Comment by zhengthomastang** [comment]
Sorry for the inconvenience, but the width and height of each cropped image are required for normalization and the computation of center and scale (necessary as input to the pose estimation model).

**Comment by lhc11171552** [comment]
Thank you so much, thank you for your help

**Comment by lhc11171552** [comment]
The value of joints does not affect the evaluation. Will the value of joints affect the generation of heatmaps?

**Comment by zhengthomastang** [comment]
@lhc11171552 They should not affect the generation of heatmaps.

**Comment by lhc11171552** [comment]
thanks a lot
