### ISSUE TITLE
Hello, I don’t seem to see the operation of multiplying the mask with the feature map to get the local features. Can you tell me where this operation is?

### ISSUE THREAD

**Issue by lhc11171552** [NVlabs/PAMTRI#4]

**Comment by zhengthomastang** [comment]
We didn't multiply the masks with feature maps. Instead, we append the segmented masks as image channels: https://github.com/NVlabs/PAMTRI/blob/master/MultiTaskNet/torchreid/dataset_loader.py#L88-L101

**Comment by lhc11171552** [comment]
The marked parts of these mask values are all 1, and the unmarked parts are all 0, right?

**Comment by zhengthomastang** [comment]
They should be in the same format as binary images (255 and 0). And they will be normalized along with the original image channels.

**Comment by lhc11171552** [comment]
So is the output value of the mask only 255 and 0?

**Comment by lhc11171552** [comment]
Or do the numbers in the mask have other values?

**Comment by lhc11171552** [comment]
Thank you for your answer, but if you just concantate the mask and the original image, can you get discriminative local information?

**Comment by zhengthomastang** [comment]
The masks are binary images with only two values. Using segments is only one of the proposed mode in the paper. You may also choose to use keypoint histograms which provide more discriminative information.

**Comment by lhc11171552** [comment]
alright, thank you very much

**Comment by lhc11171552** [comment]
Thank you for answering my questions，thanks a lot
