### ISSUE TITLE
Is there a way to change the size of the mask image, can the mask size not be 64*64? Is it possible to not output the mask map during testing? And concatenate them, because this can improve the performance of the network, if so,I hope to tell me the location of the output image in the code during the test, thank you very much!

### ISSUE THREAD

**Issue by lhc11171552** [NVlabs/PAMTRI#6]

**Comment by zhengthomastang** [comment]
To suppress the output of segments/heatmaps, you can disable the flag `--outputPreds` during inference. To change the dimension of output images, you can make changes [here](https://github.com/NVlabs/PAMTRI/blob/master/PoseEstNet/lib/core/function.py#L283).
