### ISSUE TITLE
Hello, I would like to ask whether the keypoints are marked by yourself or by the code

### ISSUE THREAD

**Issue by Anonymous-DRDL** [NVlabs/PAMTRI#9]

**Comment by zhengthomastang** [comment]
The images with keypoints labels were selected manually from the results of a baseline.

**Comment by Anonymous-DRDL** [comment]
Thank you, I actually want to know whether the actual key point position information in the csv was manually annotated or generated by code

**Comment by zhengthomastang** [comment]
The labels were generated by a baseline model but manually selected. They can be used for training and validation. But because they are only a small subset, the performance may not be good unless adding synthetic data and their labels, like what we did in the paper.

**Comment by Anonymous-DRDL** [comment]
Thank you very much, I would like to ask where is this baseline model? Can this baseline model generate keypoints for other data sets, such as vehicleid?

**Comment by zhengthomastang** [comment]
We used this repo: https://github.com/krrish94/CarKeypoints. You can also use our provided models as baselines.

**Comment by Anonymous-DRDL** [comment]
Thank you very much. In fact, I want to use this baseline to generate keypoint csv for the vehicleid data set, and use the keypoint csv to train and generate a model such as pose_hrnet_w48_256x192.pth, and use this model to do experiments. I want to know if your model can generate key information on csv? Also, do I need to download any software to run Lua code?

**Comment by zhengthomastang** [comment]
The output of our models in inference mode is in CSV format (see more details in [README.md of PoseEstNet](https://github.com/NVlabs/PAMTRI/tree/master/PoseEstNet)). I am not sure what environment you are using, but you should be able to find many tutorials for Lua online.

**Comment by Anonymous-DRDL** [comment]
Thank you very much for your answers
